oauth:
    google:
        auth_uri: https://accounts.google.com/o/oauth2/v2/auth
        client_id: google-client-id
        client_secret: google-client-secret
        grant_type: authorization_code
        redirect_uri: http://localhost:8080/google/callback
        token_url: https://oauth2.googleapis.com/token
        scopes: openid,profile,email
    kakao:
        auth_uri: https://kauth.kakao.com/auth/authorize
        client_id: kakao-client-id
        client_secret: kakao-client-id
        grant_type: authorization_code
        redirect_uri: http://localhost:8080/kakao/callback
        token_url: https://kauth.kakao.com/oauth/token
        scopes: openid,profile_nickname,profile_image,account_email