oauth:
    google:
        auth_uri: https://accounts.google.com/o/oauth2/v2/auth
        client_id: client_id
        client_secret: client_secret
        grant_type: authorization_code
        redirect_uri: http://localhost:8080/callback
        token_url: https://oauth2.googleapis.com/token
        scopes: openid,profile,email
